import { TOURNAMENT_TEAMS } from './tournamentTeams'

const teamBy = (key) => TOURNAMENT_TEAMS.find((t) => t.key === key)

export const LESSON_SLIDES = [
  {
    type: 'quiz',
    qZh: '你们知道宝可梦最早是从哪里来的吗?',
    qEn: 'Where did Pokémon come from first?',
    options: [
      { key: 'A', textZh: '动画片', textEn: 'The cartoon' },
      { key: 'B', textZh: '游戏', textEn: 'The games' },
      { key: 'C', textZh: '毛绒玩具', textEn: 'Plush toys' },
      { key: 'D', textZh: '现实世界', textEn: 'The real world' },
    ],
    answerKey: 'B',
    revealZh: '答案是 B —— 游戏! 1996 年的 Game Boy 上诞生了第一只宝可梦。',
    revealEn: 'It was B — the games! The very first Pokémon appeared on the Game Boy in 1996.',
  },
  {
    type: 'video',
    titleZh: 'Game Boy 原版开场',
    titleEn: 'The Original Game Boy Intro',
    descZh: '来看看最早的像素宝可梦长什么样子!',
    descEn: "Let's see what the very first pixel Pokémon looked like!",
    youtubeId: 'C19O5xm51dk',
  },
  {
    type: 'info',
    titleZh: '动画的诞生:小智与皮卡丘',
    titleEn: 'The Anime Is Born: Ash & Pikachu',
    bodyZh: '真正让宝可梦风靡全球的是动画片! 主角是永远 10 岁的少年「小智」，还有那只不肯进精灵球、总待在他肩膀上的皮卡丘。',
    bodyEn: "The anime made Pokémon a worldwide hit! Meet Ash — forever 10 years old — and his Pikachu, who refuses to stay in its Poké Ball and rides on his shoulder instead.",
  },
  {
    type: 'video',
    titleZh: '小智第一次遇见皮卡丘',
    titleEn: 'How Ash and Pikachu Meet',
    descZh: '他们的友情是怎么开始的?',
    descEn: 'How did their friendship begin?',
    youtubeId: 'xfnYDn4zrYk',
  },
  {
    type: 'discuss',
    titleZh: '看看你观察到了什么?',
    titleEn: 'What Did You Notice?',
    img: '/lesson/ash-pikachu.webp',
    promptZh: '视频看完啦，一起来聊聊吧!',
    promptEn: "Now that you've watched the video, let's talk about it!",
    questions: [
      { zh: '你们在视频里看到了什么?', en: 'What did you see in the video?' },
      { zh: '小智是怎么遇见皮卡丘的?', en: 'How did Ash meet Pikachu?' },
    ],
  },
  {
    type: 'journey',
    titleZh: '训练师的成长之旅',
    titleEn: "A Trainer's Journey",
    steps: [
      { icon: '📕', zh: '拿到宝可梦图鉴', en: 'Get your Pokédex' },
      { icon: 'pokeball', zh: '用精灵球收集宝可梦', en: 'Catch Pokémon with Poké Balls' },
      { icon: '⚔️', zh: '带喜欢的宝可梦跟野生宝可梦和训练师对战，升级变强', en: 'Battle wild Pokémon & trainers to level up' },
      { icon: '🏅', zh: '挑战各地道馆，收集徽章', en: 'Challenge Gyms and earn Badges' },
      { icon: '🏟️', zh: '打进大师赛', en: 'Reach the big tournament' },
      { icon: '👑', zh: '赢了就成为最终的宝可梦大师!', en: 'Win to become the ultimate Pokémon Master!' },
    ],
  },
  {
    type: 'quiz',
    qZh: '小智一共挑战了多少次地区联盟大赛，才最终成为世界冠军?',
    qEn: 'How many league tournaments did Ash enter before becoming World Champion?',
    options: [
      { key: 'A', textZh: '3 次', textEn: '3 times' },
      { key: 'B', textZh: '5 次', textEn: '5 times' },
      { key: 'C', textZh: '8 次', textEn: '8 times' },
      { key: 'D', textZh: '20 次', textEn: '20 times' },
    ],
    answerKey: 'C',
    revealZh: '一共 8 次! 前 6 次都失败了，但他从来没有放弃 —— 这就是最厉害的地方!',
    revealEn: 'Eight times! He lost the first six, but he never gave up — that is what makes him a champion.',
    img: '/lesson/champion-celebration.jpg',
  },
  {
    type: 'teams',
    titleZh: '小智的大赛队伍 (一)',
    titleEn: "Ash's Tournament Teams (1)",
    teams: [teamBy('kanto'), teamBy('johto'), teamBy('hoenn')],
  },
  {
    type: 'teams',
    titleZh: '小智的大赛队伍 (二)',
    titleEn: "Ash's Tournament Teams (2)",
    teams: [teamBy('sinnoh'), teamBy('unova'), teamBy('kalos')],
  },
  {
    type: 'teams',
    titleZh: '小智的大赛队伍 (三) —— 夺冠!',
    titleEn: "Ash's Tournament Teams (3) — Champion!",
    teams: [teamBy('alola'), teamBy('masters')],
  },
  {
    type: 'video',
    titleZh: '巅峰对决:夺得世界冠军!',
    titleEn: 'The Final Battle: World Champion!',
    descZh: '旅行了 25 年后，小智带着最强队伍迎战不败冠军丹帝，皮卡丘一锤定音!',
    descEn: 'After 25 years, Ash and his strongest team face the undefeated Champion Leon — and Pikachu seals the win!',
    youtubeId: 'sR1hzqn8k5w',
  },
  {
    type: 'evolution',
    titleZh: '进化:宝可梦会变大变强',
    titleEn: 'Evolution: Pokémon Grow Stronger',
    groups: [
      {
        titleZh: '御三家:三位伙伴都会长大变强',
        titleEn: 'The three starters all grow up',
        layout: 'chains',
        chains: [
          [
            { id: 1, nameEn: 'Bulbasaur', nameZh: '妙蛙种子' },
            { id: 2, nameEn: 'Ivysaur', nameZh: '妙蛙草' },
            { id: 3, nameEn: 'Venusaur', nameZh: '妙蛙花' },
          ],
          [
            { id: 4, nameEn: 'Charmander', nameZh: '小火龙' },
            { id: 5, nameEn: 'Charmeleon', nameZh: '火恐龙' },
            { id: 6, nameEn: 'Charizard', nameZh: '喷火龙' },
          ],
          [
            { id: 7, nameEn: 'Squirtle', nameZh: '杰尼龟' },
            { id: 8, nameEn: 'Wartortle', nameZh: '卡咪龟' },
            { id: 9, nameEn: 'Blastoise', nameZh: '水箭龟' },
          ],
        ],
      },
      {
        titleZh: '伊布家族:1 只伊布，8 种进化!',
        titleEn: 'Eevee: one Pokémon, eight evolutions!',
        layout: 'hub',
        center: { id: 133, nameEn: 'Eevee', nameZh: '伊布' },
        members: [
          { id: 134, nameEn: 'Vaporeon', nameZh: '水伊布' },
          { id: 135, nameEn: 'Jolteon', nameZh: '雷伊布' },
          { id: 136, nameEn: 'Flareon', nameZh: '火伊布' },
          { id: 196, nameEn: 'Espeon', nameZh: '太阳伊布' },
          { id: 197, nameEn: 'Umbreon', nameZh: '月亮伊布' },
          { id: 470, nameEn: 'Leafeon', nameZh: '叶伊布' },
          { id: 471, nameEn: 'Glaceon', nameZh: '冰伊布' },
          { id: 700, nameEn: 'Sylveon', nameZh: '仙子伊布' },
        ],
      },
    ],
  },
  {
    type: 'image',
    titleZh: '更强大的形态:Mega 与超极巨化',
    titleEn: 'Even Stronger: Mega & Gigantamax',
    src: '/lesson/mega-gigantamax-forms.jpg',
    captionZh: '进化之后还能变得更强! 御三家可以「超级进化」(Mega)，也能「超极巨化」变得超级大。',
    captionEn: 'Beyond evolution! The Kanto starters can Mega Evolve and even Gigantamax into giant forms.',
  },
  {
    type: 'quiz',
    qZh: '属性克制就像石头剪刀布:💧水克火🔥、🔥火克草🌿、🌿草克水💧。那么小火龙(火)遇到杰尼龟(水)，谁会赢?',
    qEn: 'Types work like rock-paper-scissors: Water beats Fire, Fire beats Grass, Grass beats Water. So if Charmander (Fire) meets Squirtle (Water), who wins?',
    options: [
      { key: 'A', textZh: '小火龙 (火)', textEn: 'Charmander (Fire)' },
      { key: 'B', textZh: '杰尼龟 (水)', textEn: 'Squirtle (Water)' },
    ],
    answerKey: 'B',
    revealZh: '杰尼龟赢! 水能灭火，所以水克火。💧 > 🔥',
    revealEn: 'Squirtle wins! Water puts out fire, so Water beats Fire. 💧 > 🔥',
  },
  {
    type: 'image',
    titleZh: '完整的 18 种属性相克表',
    titleEn: 'All 18 Types: Full Matchup Chart',
    src: '/lesson/type-chart.jpg',
    captionZh: '其实一共有 18 种属性，它们互相都有克制关系。不用全记住，多玩几次就熟啦!',
    captionEn: "There are 18 types in all, and they all beat or lose to one another. No need to memorize — you'll learn them by playing!",
  },
  {
    type: 'transition',
    titleZh: '游戏时间!',
    titleEn: 'Game Time!',
    bodyZh: '现在你已经认识了进化、属性和小智的故事 —— 来玩「猜猜这是谁?」吧!',
    bodyEn: "Now you know evolution, types, and Ash's story — let's play Who's That Pokémon!",
    buttonZh: '开始猜猜看',
    buttonEn: "Play Who's That Pokémon",
  },
]
