// 小智历代地区联盟大赛队伍。id 为全国图鉴编号，立绘走 pokeapi.spriteUrl(id)。
const PIKACHU = { id: 25, nameEn: 'Pikachu', nameZh: '皮卡丘' }

export const TOURNAMENT_TEAMS = [
  {
    key: 'kanto',
    regionEn: 'Kanto League',
    regionZh: '关都联盟',
    resultEn: 'Top 16',
    resultZh: '16 强',
    championship: false,
    members: [
      PIKACHU,
      { id: 1, nameEn: 'Bulbasaur', nameZh: '妙蛙种子' },
      { id: 6, nameEn: 'Charizard', nameZh: '喷火龙' },
      { id: 7, nameEn: 'Squirtle', nameZh: '杰尼龟' },
      { id: 99, nameEn: 'Kingler', nameZh: '巨钳蟹' },
      { id: 89, nameEn: 'Muk', nameZh: '臭臭泥' },
    ],
  },
  {
    key: 'johto',
    regionEn: 'Johto League',
    regionZh: '城都联盟',
    resultEn: 'Top 8',
    resultZh: '8 强',
    championship: false,
    members: [
      PIKACHU,
      { id: 214, nameEn: 'Heracross', nameZh: '赫拉克罗斯' },
      { id: 153, nameEn: 'Bayleef', nameZh: '月桂叶' },
      { id: 155, nameEn: 'Cyndaquil', nameZh: '火球鼠' },
      { id: 158, nameEn: 'Totodile', nameZh: '小锯鳄' },
      { id: 164, nameEn: 'Noctowl', nameZh: '猫头夜鹰' },
    ],
  },
  {
    key: 'hoenn',
    regionEn: 'Hoenn League',
    regionZh: '丰缘联盟',
    resultEn: 'Top 8',
    resultZh: '8 强',
    championship: false,
    members: [
      PIKACHU,
      { id: 254, nameEn: 'Sceptile', nameZh: '蜥蜴王' },
      { id: 277, nameEn: 'Swellow', nameZh: '大王燕' },
      { id: 341, nameEn: 'Corphish', nameZh: '龙虾小兵' },
      { id: 324, nameEn: 'Torkoal', nameZh: '煤炭龟' },
      { id: 362, nameEn: 'Glalie', nameZh: '冰鬼护' },
    ],
  },
  {
    key: 'sinnoh',
    regionEn: 'Sinnoh League',
    regionZh: '神奥联盟',
    resultEn: 'Top 4',
    resultZh: '4 强',
    championship: false,
    members: [
      PIKACHU,
      { id: 392, nameEn: 'Infernape', nameZh: '烈焰猴' },
      { id: 389, nameEn: 'Torterra', nameZh: '土台龟' },
      { id: 398, nameEn: 'Staraptor', nameZh: '姆克鹰' },
      { id: 418, nameEn: 'Buizel', nameZh: '泳圈鼬' },
      { id: 443, nameEn: 'Gible', nameZh: '圆陆鲨' },
    ],
  },
  {
    key: 'unova',
    regionEn: 'Unova League',
    regionZh: '合众联盟',
    resultEn: 'Top 8',
    resultZh: '8 强',
    championship: false,
    members: [
      PIKACHU,
      { id: 553, nameEn: 'Krookodile', nameZh: '流氓鳄' },
      { id: 499, nameEn: 'Pignite', nameZh: '炒炒猪' },
      { id: 495, nameEn: 'Snivy', nameZh: '藤藤蛇' },
      { id: 501, nameEn: 'Oshawott', nameZh: '水水獭' },
      { id: 521, nameEn: 'Unfezant', nameZh: '轰隆雉' },
    ],
  },
  {
    key: 'kalos',
    regionEn: 'Kalos League',
    regionZh: '卡洛斯联盟',
    resultEn: 'Runner-up',
    resultZh: '亚军 · 差一点点!',
    championship: false,
    members: [
      PIKACHU,
      { id: 658, nameEn: 'Greninja', nameZh: '甲贺忍蛙' },
      { id: 663, nameEn: 'Talonflame', nameZh: '烈箭鹰' },
      { id: 701, nameEn: 'Hawlucha', nameZh: '摔角鹰人' },
      { id: 706, nameEn: 'Goodra', nameZh: '黏美龙' },
      { id: 715, nameEn: 'Noivern', nameZh: '音波龙' },
    ],
  },
  {
    key: 'alola',
    regionEn: 'Alola League',
    regionZh: '阿罗拉联盟',
    resultEn: '🏆 Champion',
    resultZh: '🏆 初代冠军',
    championship: true,
    members: [
      PIKACHU,
      { id: 727, nameEn: 'Incineroar', nameZh: '炽焰咆哮虎' },
      { id: 745, nameEn: 'Lycanroc', nameZh: '鬃岩狼人' },
      { id: 722, nameEn: 'Rowlet', nameZh: '木木枭' },
      { id: 809, nameEn: 'Melmetal', nameZh: '美录梅塔' },
      { id: 804, nameEn: 'Naganadel', nameZh: '四颚针龙' },
    ],
  },
  {
    key: 'masters',
    regionEn: 'World Coronation Series',
    regionZh: '世界锦标赛',
    resultEn: '🏆 World Champion',
    resultZh: '🏆 八大师赛 · 世界第一',
    championship: true,
    members: [
      PIKACHU,
      { id: 149, nameEn: 'Dragonite', nameZh: '快龙' },
      { id: 94, nameEn: 'Gengar', nameZh: '耿鬼' },
      { id: 448, nameEn: 'Lucario', nameZh: '路卡利欧' },
      { id: 865, nameEn: "Sirfetch'd", nameZh: '葱游兵' },
      { id: 882, nameEn: 'Dracovish', nameZh: '鳃鱼龙' },
    ],
  },
]
